### ISSUE TITLE
CloudFlare serving anonymous content to authenticated users?

### ISSUE THREAD

**Issue by hvelarde** [collective/wildcard.cloudflare#3]
Correct me if I'm wrong but seems that CloudFlare is not aware of Plone authentication; have you seen this behavior before?

**Comment by vangheem** [comment]
You mean so that it will not cache when you are logged in?

Depends. Default free cloudflare accounts don't cache html anyways.

At some of the higher paid levels, you can more options with "Page rules". One of those options is "Bypass cache cookie" which is configurable.

Let me know if you have any other questions. Closing the ticket though.

**Comment by hvelarde** [comment]
I mean that CloudFlare is returning cached pages that should be available only to anonymous users to authenticated users and they have to use Ctrl+F5 all the time to reload the page.

I was wondering if we can set some header on the request to avoid this behavior and I was wondering if this package is a good place to do it.

**Comment by vangheem** [comment]
This package only has to do with invalidation. 

I'm not sure how you have cloudflare configured but if ctrl + f5 is clearing it, it sounds like cloudflare or plone.app.caching is sending cache headers to tell the browser to cache the page, not the proxy. Make sure in plone.app.caching settings to check the box to only cache for anonymous users. Also, inspect the cache headers.

AFAIK, free version of cloudflare does not cache html though so it could just be a plone.app.caching configuration problem.

**Comment by hvelarde** [comment]
thanks, seems to be nginx doing some caching things I wouldn't expect on my configuration; I'll check further.

**Comment by hvelarde** [comment]
just for the record: I was missing the `$cookie___ac` in the following configuration line of nginx:

    proxy_cache_bypass $http_cache_control $cookie___ac;
